### ISSUE TITLE
subdirectories problem

### ISSUE THREAD

**Issue by mahmutoktay** [jamesbontempo/njodb#19]
Initially, I want to create two subdirectories within the database folder and collect the information in different folders. However, the information is added under the data in the data.0.json file created in the mydata folder. In this case, shouldn't a subfolder named "ayar" be created and the data saved there? What am I doing wrong. thanks a lot

```
const njodb = require("njodb");
const testDB = new njodb.Database("./testdb/",  { datadir : "mydata" ,  datastores : 1 });
const ayarDB = new njodb.Database("./testdb/",  { datadir : "ayar" ,  datastores : 1 });

const data = [
    {
        id: 1,
        ayar: "github",
        durum: true
    },
    {
        id: 2,
        ayar: "facebook",
        durum: true
    },
    {
        id: 3,
        ayar: "google",
        durum: true
    }
];

const data2 = [
    {
        id: 1,
        ayar: "twitter",
        durum: true
    },
    {
        id: 2,
        ayar: "instagram",
        durum: true
    },
    {
        id: 3,
        ayar: "meta",
        durum: true
    }
];

testDB.insert(data).then(results => console.log(results) );
ayarDB.insert(data2).then(results => console.log(results) );
```

result to testdb/mydata/data.0.json  (There is no subfolder named "ayar")
```
{"id":1,"ayar":"github","durum":true}
{"id":2,"ayar":"facebook","durum":true}
{"id":3,"ayar":"google","durum":true}
{"id":1,"ayar":"twitter","durum":true}
{"id":2,"ayar":"instagram","durum":true}
{"id":3,"ayar":"meta","durum":true}
```

**Comment by jamesbontempo** [comment]
You can't have a single database root with two different data subdirectories because there is only one `njodb.properties` file per root, and it only has one `datadir` property. If you want to keep data in different places, then you need two databases, each with their own unique root directory & separate `njodb.properties` files. In your example you would need to do something like:
```
const testDB = new njodb.Database("./testdb1/",  { datadir : "mydata" ,  datastores : 1 });
const ayarDB = new njodb.Database("./testdb2/",  { datadir : "ayar" ,  datastores : 1 });
```
See how the root directories are different?

**Comment by jamesbontempo** [comment]
Alternatively, you could have a single database but add a property to each record that would distinguish the source. For example:
```
const data = [
    {source: "mydata", id: 1, ayar: "github", durum: true},
    {source: "mydata", id: 2, ayar: "facebook", durum: true},
    {source: "mydata", id: 3, ayar: "google", durum: true}
];

const data2 = [
    {source: "ayar", id: 1, ayar: "twitter", durum: true},
    {source: "ayar", id: 2, ayar: "instagram", durum: true},
    {source: "ayar", id: 3, ayar: "meta", durum: true}
];
```
Then you could supply the `source` value in a `selecter` to select data for the appropriate source; for example:
```
db.select(r => r.source === "ayar");
```
Ultimately, as the documentation describes, `njodb` is completely schema-less. This means that you can think of the data as existing in one single collection, like a large bag of data (but a bag that has partitions so you can work on more than one of them at a time in parallel).

**Comment by mahmutoktay** [comment]
I understand very well. Thanks a lot

**Comment by jamesbontempo** [comment]
Great, I'm glad that's clear :)
