### ISSUE TITLE
Sort and Limit

### ISSUE THREAD

**Issue by paradis-A** [jamesbontempo/njodb#4]
How do I perform sort or limit?

**Comment by jamesbontempo** [comment]
Hello @paradis-A.

The easiest way to perform a sort or limit is to use JavaScript's built-in [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) and [slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) functions on the `data` array returned from a `select` or `selectSync` call.

To sort data by comparing the values of a specific property/field:
```
const sortedData = db.selectSync(() => true)
  .data.sort((a,b) => {
    if (a.property < b.property) {return -1};
    if (a.property > b.property) {return 1};
    return 0;}
  );
```

To limit the number of records returned (in this example, the first 10 records):
```
const limitedData = db.selectSync(() => true)
  .data.slice(9);
```

You could chain them, too, to sort the data then retrieve the first 10 records:
```
const sortedAndLimitedData = db.selectSync(() => true)
  .data
    .sort((a,b) => {
      if (a.property < b.property) {return -1};
      if (a.property > b.property) {return 1};
      return 0;
    })
    .slice(9);
```

Of course, you can write any sort of custom sort function you want, and also use additional parameters for slice to return the specific subset of the data that is of interest.

I hope this makes sense & is helpful!

**Comment by paradis-A** [comment]
@jamesbontempo that's awesome. It really feels like LINQ. Your work is truly a hidden gem I'm glad i discovered your masterpiece. Keep up the good work man. I'll be doing typescript declaration on my freetime.

**Comment by jamesbontempo** [comment]
Glad that helped @paradis-A! And thanks for the kind words :) Feel free to tell all your friends about njodb :P And let me know if there are any features that you think would be good additions to the software, or enhancements that would make using it easier. Best of luck with the TypeScript work...
